partida:
	python3 -c 'from partida import Partida;  \
	p = Partida(); \
	p.crear_partida([(10, 0), (10, 0), (10, 0), (10, 0), (10, 0), (10, 0), (10, 0), (10, 0), (10, 0), (10, 10, 10)]);  \
	print("\nLa puntuacion total de la partida es:", p.puntuacion_total(),"\n")'