cli3_python2:
	python3 app2_python/cli3.py

serv3_python2:
	rm -rf prueba_fifo
	python3 app2_python/serv3.py

	
cli3_ruby:
	ruby app_2_ruby/cliente/lib/main.rb

serv3_ruby:
	ruby app_2_ruby/servidor/lib/main.rb

all:
	@echo "Compilación y ejecución de la práctica"

clean:
	@echo "Limpiando..."

